#include "lex.yy.c"  // This file is generated by Lex
#include "y.tab.c"  // This file is generated by Yacc/Bison


int main() {
    // Code from the original main function of the lexer
    char input[10000];
    printf("Enter input: ");
    scanf("%s", input);
    yyin = fopen(input, "r");
    if (yyin == NULL) {
        printf("Error opening the file. Please check the file path.\n");
        return 1;
    }

    // Code from the original do-while loop calling the lexer
    int token;
    do {
        token = yylex();
    } while (token != 0);

    // Code from the original main function of the parser
    yyparse();

    // Additional code if needed

    printf("Total lines: %d\n", line_count);
    return 0;
}